version: "3"
services:
    mysql:
        image: mysql:8.0.12
        environment:
          - MYSQL_ROOT_PASSWORD=twitter
        ports:
          - "3306:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
